name = "SVDSketch"
uuid = "f2712ddf-d375-4b75-9475-5f3be79dfb12"
authors = ["Xu Feng", "Wenjian Yu", "Pengfei Zhu"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
