name = "SVDSketch"
uuid = "f2712ddf-d375-4b75-9475-5f3be79dfb12"
authors = ["Xu Feng", "Wenjian Yu", "Pengfei Zhu"]
version = "0.1.1"

[deps]
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ElasticArrays = "1"
julia = "1.3"

[extras]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SparseArrays", "StableRNGs"]
